# Generated by Django 4.1.3 on 2022-11-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quesmodel_author_quesmodel_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 19, 6, 11, 813685, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
